import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import { Nunito_Sans } from "next/font/google"
import React from "react"
import "./globals.css"

const nunito = Nunito_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<React.PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={cn(nunito.className, "dark")}>
        {children}
      </body>
    </html>
  )
}
