export const colors: { [k: string]: string } = {
    gray: "text-notion-gray",
    brown: "text-notion-brown",
    orange: "text-notion-orange",
    yellow: "text-notion-yellow",
    teal: "text-notion-teal",
    blue: "text-notion-blue",
    purple: "text-notion-purple",
    pink: "text-notion-pink",
    red: "text-notion-red",
    gray_background: "bg-notion-gray-muted",
    brown_background: "bg-notion-brown-muted",
    orange_background: "bg-notion-orange-muted",
    yellow_background: "bg-notion-yellow-muted",
    teal_background: "bg-notion-teal-muted",
    blue_background: "bg-notion-blue-muted",
    purple_background: "bg-notion-purple-muted",
    pink_background: "bg-notion-pink-muted",
    red_background: "bg-notion-red-muted",
}
